---
title: "First Knit"
author: "Genesis Alfaro"
output: 
  html_document:
    number_sections: true
    toc: true
    toc_depth: 5
date: "`r Sys.Date()`"   
---

# A Little Survey

Here are just a few questions so I can get to know you and so you can get practice submitting an assignment in Canvas.  For each question, insert your answer underneath. Make sure each answer is at the minimum a complete sentence with correctly spelled words and correct puncuation. 

## A short history of you.  
Where did you attend High School, and did you graduate? Compare english class to math, is one easier for you than the other? Finally which subject did you do the best in? Your answer should have at least two sentences devoted to each question.  
  
### my answer      
I attended two high schools, the first was Palmdale High School. I was there my freshman year all the way up to my sophomore year. Then I went to R. Rex Parris high school for junior and senior year where I graduated. I believe English is a lot easier than math and a bit more interesting to me.
   

     


## Your computer and your and its capability?  
 For this class  you need a computer you can use at home.  So, what kind is it (windows, Apple, Linux)?  On a scale of 1 to 10, where 1 is a total dummy (doesn't know a mouse from a keyboard) and 10 is a complete geek (knows computer stuff in and out) How do you rate yourself?  You also need to have have internet access. How is your connection to the internet where you live?

### my answer   
Well for now I don't have a computer or laptop at all but I do plan on getting one. I was thinking of getting a windows laptop, but in the meantime I'll be using my mom's home computer. I also do have internet access at home, and on a scale 1 to 10 I'd rate myself a solid 5 right in the middle.
  
   

## Others and You?   
What name do you prefer to be called by your classmates and instructor, if your buddys call you something but you want people in the class to call you something else - what would that be? 

### my answer     
My name is Genesis but my friends and family call me Gen. I don't mind being called either one.  
   
 




## Aspirations?   
What do you want to achieve in life?  What college subject do you think would be of the greatest interest to you? What degree or certificate are you trying to achieve?

### my answer     
If I'll be very honest i still don't really know exactly what I want to do in life career wise but I do know I want to do something that I enjoy doing. For now I'm focusing on taking children development classes as my major, I'm trying to achieve a degree in something where I work with young kids.   
   
 




## Past adventures?  
Have you ever gone to foreign countries, if so which ones, if not Where might you go in the future?  Have you ever been in the military, if so which branch, if not which branch would you choose if you got drafted, and why?

### my answer     
I've only been to El Salvador to visit family, I've been out there about 4 times my whole life. I love it so much, I miss going to visit family, having beach days, riding in the back of trucks feeling the air brush through hair. I hope to visit soon again. I have also never been in military nor am I planning on it, I solute those who are brave and strong enough to do so.  
   
  




## Why are you taking Statistics?  
Did you take Math 115 or Math 116 ?  Did you know Math 115 only satisfies a general education requirement but that Math 116 counts as taking statistics in several transfer institutions??  
What grade do you need to attain in stats to not upset your future plans, What is your plan?  
 

### my answer
I'm currently taking math 116, I've never heard of statistics anything. I know what you're thinking as if I lived under a rock, but I'm just being real and honest. However, I'm always willing to learn new things and better and further my knowledge/ education.
  
   
 






  




